// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpUQ5IxEYi3Xk1ln2rbOokT_CvcaTFLE',
    appId: '1:142720913420:web:adceec9d22ecceba0f9e29',
    messagingSenderId: '142720913420',
    projectId: 'flutter-todo-provider-46b6a',
    authDomain: 'flutter-todo-provider-46b6a.firebaseapp.com',
    storageBucket: 'flutter-todo-provider-46b6a.firebasestorage.app',
    measurementId: 'G-FGC099KMJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYNWAqceXSFWx0mWHzM0JQ-3CesGi2_jg',
    appId: '1:142720913420:android:b7fedbdd017c10ea0f9e29',
    messagingSenderId: '142720913420',
    projectId: 'flutter-todo-provider-46b6a',
    storageBucket: 'flutter-todo-provider-46b6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPD66t-uZ_2SVqzqWq7ugCXu_pO615k7U',
    appId: '1:142720913420:ios:03db968316736f9f0f9e29',
    messagingSenderId: '142720913420',
    projectId: 'flutter-todo-provider-46b6a',
    storageBucket: 'flutter-todo-provider-46b6a.firebasestorage.app',
    iosBundleId: 'com.example.todolistProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPD66t-uZ_2SVqzqWq7ugCXu_pO615k7U',
    appId: '1:142720913420:ios:03db968316736f9f0f9e29',
    messagingSenderId: '142720913420',
    projectId: 'flutter-todo-provider-46b6a',
    storageBucket: 'flutter-todo-provider-46b6a.firebasestorage.app',
    iosBundleId: 'com.example.todolistProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEpUQ5IxEYi3Xk1ln2rbOokT_CvcaTFLE',
    appId: '1:142720913420:web:35fcc943056047b60f9e29',
    messagingSenderId: '142720913420',
    projectId: 'flutter-todo-provider-46b6a',
    authDomain: 'flutter-todo-provider-46b6a.firebaseapp.com',
    storageBucket: 'flutter-todo-provider-46b6a.firebasestorage.app',
    measurementId: 'G-LP2EFZT8BL',
  );
}
